/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'bio' : string,
  'tagline' : string,
  'name' : string,
  'contactEmail' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'createdAt' : bigint,
  'year' : bigint,
  'description' : string,
  'imageIds' : Array<string>,
  'category' : string,
  'location' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdminIfNoneExists' : ActorMethod<[], UserRole>,
  'createProject' : ActorMethod<
    [string, string, string, bigint, string, Array<string>, boolean],
    bigint
  >,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'getAboutContent' : ActorMethod<[], AboutContent>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getFeaturedProjects' : ActorMethod<[], Array<Project>>,
  'getProjectById' : ActorMethod<[bigint], Project>,
  'getProjectsByCategory' : ActorMethod<[string], Array<Project>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'init' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderProjects' : ActorMethod<[Array<bigint>], undefined>,
  'resetAndClaimAdmin' : ActorMethod<[], UserRole>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfRegister' : ActorMethod<[], UserRole>,
  'submitContactMessage' : ActorMethod<[string, string, string], bigint>,
  'updateAboutContent' : ActorMethod<[AboutContent], undefined>,
  'updateProject' : ActorMethod<
    [bigint, string, string, string, bigint, string, Array<string>, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];